### ISSUE TITLE
GenCons consensus generation: call N instead of non-variable site

### ISSUE THREAD

**Issue by keyfm** [subwaystation/TOPAS#1]
Hi Simon,
I would like to use GenCons on my SNP/Indel file to build a consensus. However, I noticed that only variable positions (e.g. SNPs) will show up in the resulting consensus file, while non-variable sites are put as "N", even though coverage criteria etc. would allow the variants to pass. Comparing my *vcfs with another older but working *vcf from a colleague reveals that the difference is the Format or the Genotype column. The GenCons tool is working when the vcf genotype-format for invariable sites is as followed: "GT:DP" but in my case the format is "GT:AD:DP". Could you adapt the code so it will extract the data required for calculation based on the Format column in the vcf rather than hard coded (which I think it is doing right now). Please let me know.
felix

**Comment by subwaystation** [comment]
Hi Felix,
could you please provide an example file?

Thanks :+1:

**Comment by keyfm** [comment]
Hi Simon,
Find sample attached. As said, your code should define the field relevant to extract DP info from the FORMAT field. Guess that is the reason why it has been added to every line. I am running GATK version 3.8 which includes the AD field to non-variable sites.

Thanks and all the best,
Felix

**Comment by keyfm** [comment]
Fixed by any chance?

**Comment by subwaystation** [comment]
Sorry, I am very busy these days.... I already told James that it would be more convenient for me, if a HiWi of yours could do that ;)

Also I do not see your attachment anywhere? Did I miss it somehow?

**Comment by subwaystation** [comment]
Is this still an issue? Else I am closing it.

**Comment by keyfm** [comment]
as I wrote a fix around it I do not know. if your code uses the FORMAT field to identify the relevant GENOTYPE fields in newest version all should be good. when I reported the bug I had used an older version present on the SHH cluster

**Comment by subwaystation** [comment]
I see this as resolved. 
If you should run into this again, just open the issue.
