### ISSUE TITLE
Create a Gradle/Maven script?

### ISSUE THREAD

**Issue by apeltzer** [subwaystation/TOPAS#3]
Could you maybe add a simple gradle or maven build script for this? 

https://github.com/apeltzer/EAGER-GUI/blob/master/build.gradle
(also check out the `settings.gradle` file in the same repository)

I'd ldike to package this using bioconda at some point and will require a.) proper versioning (could be 1.0 if you want, cf https://semver.org/ ) and b.) a proper release. 

This would make both a.) and b.) easier ;-)

**Comment by subwaystation** [comment]
Solved via #7.

Have Fun @apeltzer !
