### ISSUE TITLE
Create a bioconda recipe for this

### ISSUE THREAD

**Issue by apeltzer** [subwaystation/TOPAS#4]

**Comment by apeltzer** [comment]
Once this is in, you will get a fancy badge available on bioconda:

https://github.com/bioconda/bioconda-recipes/pull/10898

**Comment by apeltzer** [comment]
e.g. something like this:

[![install with bioconda](https://img.shields.io/badge/install%20with-bioconda-brightgreen.svg?style=flat-square)](http://bioconda.github.io/recipes/topas/README.html)

which you could then add to your `README.md` to make users aware that they can install the tool that easy now ;-) 

\+ I can install it for EAGER2 quite easily too by just running 

`conda install topas`

**Comment by subwaystation** [comment]
As soon as your pull request has been approved, I think?

**Comment by apeltzer** [comment]
Like now ;-) You can add that to your readme already, it will be functional once the upload has finished.

**Comment by subwaystation** [comment]
Thank you very much. The badge is there now ;)
